version: '3.3'

services:
    db:
        image: postgres:13.1-alpine
        restart: unless-stopped
        volumes:
            - postgres_data:/var/lib/postgresql/data
        env_file:
            - ./.env
    redis:
        restart: unless-stopped
        image: redis:7.0.5-alpine 
        expose:
            - 6379
        depends_on:
            - db
    django_server:
        restart: unless-stopped
        build:
            context: .
            dockerfile: backend/cyourself/Dockerfile
        entrypoint: /docker/backend/serverentrypoint.sh
        volumes:
            - static_volume:/backend/cyourself/static
            - media_volume:/backend/cyourself/media
        expose:
            - 8000
        depends_on:
            - db
            - redis
    nginx:
        restart: always
        image: nginx:1.21.3-alpine
        ports:
            - 80:80
        volumes:
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - static_volume:/cyourself/static
            - media_volume:/cyourself/media
        depends_on:
                - db
                - redis
                - django_server
    worker:
        restart: unless-stopped
        build:
            context: .
            dockerfile: backend/cyourself/Dockerfile
        entrypoint: /docker/backend/worker-entrypoint.sh
        volumes:
            - static_volume:/app/long/django_static
        env_file:
          - ./.env
        depends_on:
            - db
            - redis
            - django_server
            - nginx

volumes:
    static_volume:
    media_volume:
    postgres_data:
