# Generated by Django 4.1 on 2024-04-01 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("personal", "0003_follow_follow_one_time_follow_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="follow",
            name="following",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="following",
                to="personal.profile",
            ),
        ),
    ]
